apiVersion: v1
kind: LimitRange
metadata:
  name: pipeline-resource-limits
spec:
  limits:
  - defaultRequest: # this section defines default requests
      memory: "500Mi"
      cpu: "250m"
    max: # max and min define the limit range
      memory: "4Gi"
      cpu: "2"
    type: Container  